# Dataset parameters
dataset:
  size: 12
  languages: ["EN", "FR", "AR"]
  noise_percentage: 20
  max_words: 500

# Model configuration
model:
  name: "Qwen/Qwen3-8B" # VLLM model ID

# Categories of food insecurity - from Balashankaretal.,Sci.Adv.9,eabm3449(2023)
categories:
  - conflict and violence
  - political instability
  - humanitarian aid
  - economic issues
  - production shortage
  - weather conditions
  - food crisis
  - land-related issues
  - pests and disease
  - forced displacement
  - environmental issues

# Geographic regions and countries 
regions:
  - name: East Africa
    countries: [Somalia, Ethiopia, Kenya, South Sudan, Sudan]
  - name: West Africa
    countries: [Nigeria, Niger, Mali, Burkina Faso, Chad]
  - name: Middle East
    countries: [Yemen, Syria, Lebanon, Iraq]
  - name: Central Africa
    countries: [Democratic Republic of Congo, Central African Republic, Cameroon]
  - name: Southern Africa
    countries: [Zimbabwe, Mozambique, Malawi]