# Agentic Article Refinement System Configuration

# Default model configuration - a fallback for any model not specified in the agent-specific configurations
model:
  name: "google/gemma-3-4b-it"
  temperature: 0.7
  max_tokens: 2048

# System cycles and evaluation parameters
system:
  max_iterations: 3
  evaluation_threshold: 7.0  # Minimum acceptable score (out of 10)
  rag_results_count: 5      # Number of reference articles to retrieve
  human_feedback_interval: 2 # Ask for human feedback every N iterations

# Logging configuration
logging:
  level: "INFO"
  log_to_file: true
  log_file: "logs/agentic_refinement.log"

# Agent-specific configurations
agents:
  proposer: # initial article proposal
    temperature: 0.6
    max_tokens: 4096 # autoregressive sampling - must be large enough to accommodate prompt + response
    model: "Qwen/Qwen3-8B" # VLLM model ID
    enable_reasoning: false

  reviewer:
    temperature: 0.2  # Lower temperature for more consistent evaluations
    max_tokens: 1024
    model: "google/gemma-3-4b-it"
  
  reviser:
    temperature: 0.4  # Moderate temperature for creativity with consistency
    max_tokens: 1024
    model: "google/gemma-3-4b-it"

# Weights & Biases integration
wandb:
  enabled: true
  project: "agentic-article-refinement"
  entity: "reallyblaised"
  tags: ["article-refinement", "rag", "agentic"]